name: BEEKEEP
theme:
site: https://www.beekeep.us/
collections_dir: shop
collections:
    stickers:
        layout: stickers
        title: Stickers
        output: true
    performance:
        layout: performance
        title: Performance
        output: true
    clothing:
        layout: clothing
        title: clothing
        output: true
